<header>
    <h1><?= $titulek ?></h1>
</header>
<section>
    <h4>Autor: <?= $author ?></h4>
    <h4>Abstrakt:</h4>
    <?= $obsah ?><br />

    <?php if ($file != "uploads/") : ?>
        <a href="<?= $file ?>"><h4>Celý článek v PDF</h4></a>
    <?php endif ?>

    <br /><br />

    <!-- prihlaseny uzivatel -->
    <?php if (isset($role)) : ?>

        <!-- recenze -->
        <h4>Recenze:</h4>
        <?php foreach ($reviews as $review) : ?>
            <tr>
                <td>
                    Relevantnost: <?= $review['criterium_1'] ?>
                    Kvalita článku: <?= $review['criterium_2'] ?>
                    Nezaujatost: <?= $review['criterium_3'] ?>
                    Poznámka: <?= $review['note'] ?><br />
                </td>
            </tr>
        <?php endforeach ?>

        <br />

        <!-- recenzent -->
        <?php if (isset($role) && $role == 1) : ?>
            <a href="review/<?= $clanky_id ?>">Vložit recenzi</a>
        <?php endif ?>

    <?php endif ?>

    <br />
    <br />
    <br />
    <br />
    <br />

</section>
