<h1>Přidělování článků k recenzi</h1>

<!-- recenzent -->
<?php if ($role == 1) : ?>
    <h4>Přidělené články k recenzi:</h4>
    <table>
        <?php foreach ($assignments as $assignment) : ?>
            <tr>
                <td>
                    <?php if ($user_id == $assignment['user_id']) : ?>

                        <?php foreach ($clanky as $clanek) : ?>
                            <!-- odkaz na odpovidajici clanek -->
                            <?php if ($clanek['clanky_id'] == $assignment['article_id']) : ?>
                                <a href="clanek/<?= $clanek['url'] ?>"><?= $clanek['titulek'] ?></a> (ID článku: <?= $clanek['clanky_id']?>)
                            <?php endif ?>
                        <?php endforeach ?>

                    <?php endif ?>

                </td>
            </tr>
        <?php endforeach ?>
    </table>
    <br>
<?php endif ?>


<!-- admin -->
<?php if ($role == 2) : ?>
    <h4>Přidělené články k recenzi:</h4>
    <table>
        <?php foreach ($assignments as $assignment) : ?>
            <tr>
                <td>
                    ID uživatele: <?= $assignment['user_id']?>, ID článku: <?= $assignment['article_id']?>
                    <a href="assignments/<?= $assignment['assignment_id'] ?>/odstranit">Odstranit</a>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
    <br>

    <h4>Seznam recenzentů:</h4>
    <table>
        <?php foreach ($reviewers as $reviewer) : ?>
            <tr>
                <td>
                    <?= $reviewer['jmeno']?> (ID uživatele: <?= $reviewer['user_id']?>)
                </td>
            </tr>
        <?php endforeach ?>
    </table>
    <br>

    <h4>Seznam neschválených článků:</h4>
    <table>
        <?php foreach ($clanky as $clanek) : ?>
            <tr>
                <td>
                    <!-- clanek je v recenznim rizeni -->
                    <?php if ($clanek['stav'] == 0) : ?>
                        <a href="clanek/<?= $clanek['url'] ?>"><?= $clanek['titulek'] ?></a> (ID článku: <?= $clanek['clanky_id']?>)
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
    <br>
    <br>

    <h4>Přidělování článků k recenzi:</h4>
    <form method="post" enctype="multipart/form-data">
        <input type="hidden" name="assignment_id" />

        <div class="form-group">
            <label for="user_id">ID uživatele:</label>
            <input type="number" class="form-control" placeholder="Vložte ID uživatele" required name="user_id">
        </div>
        <div class="form-group">
            <label for="article_id">ID článku:</label>
            <input type="number" class="form-control" placeholder="Vložte ID článku" required name="article_id">
        </div>

        <button type="submit" value="Uložit přidělení" class="btn btn-primary">Uložit přidělení</button>

    </form>

<?php endif ?>

<br>
<br>

