<h1>Přihlášení</h1>

<form method="post">

    <div class="form-group">
        <label for="jmeno">Jméno:</label>
        <input type="text" class="form-control" placeholder="Vložte jméno" name="jmeno">
    </div>
    <div class="form-group">
        <label for="">Heslo:</label>
        <input type="password" class="form-control" placeholder="Vložte heslo" name="heslo">
    </div>

    <button type="submit" value="Přihlásit" class="btn btn-primary">Přihlásit</button>

</form>

<br>
<p>Ještě nemáte účet? <a href="register">Zaregistrujte se</a>.</p>