<h1>Registrace</h1>

<form method="post">

    <div class="form-group">
        <label for="email">Jméno:</label>
        <input type="text" class="form-control" placeholder="Vložte jméno" name="jmeno">
    </div>
    <div class="form-group">
        <label for="pwd">Heslo:</label>
        <input type="password" class="form-control" placeholder="Vložte heslo" name="heslo">
    </div>
    <div class="form-group">
        <label for="pwd">Heslo znovu:</label>
        <input type="password" class="form-control" placeholder="Vložte heslo znovu" name="heslo_znovu">
    </div>

    <button type="submit" value="Registrovat" class="btn btn-primary">Registrovat</button>


</form>
<br>